site_name: CMPE131 Website Documentation
site_url: http://BP2470.github.io/CMPE131-Website
site_author: Brian Pham

repo_name: CMPE131-Website
repo_url: https://github.com/BP2470/CMPE131-Website
edit_uri: edit/master/project/docs
docs_dir: docs

nav:
    - Home: index.md
    - API: api.md
    - About: about.md

theme: readthedocs
